spring:
  profiles:
    default: local
---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://localhost:3306/kbo_pitcher
    driver-class-name: org.mariadb.jdbc.Driver
    username: kbo_pitcher
    password: qwe123!@#

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #defer-datasource-initialization: true #(2.5~) Hibernate ??? ?? data.sql ??

  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/kboPitcher
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  sql:
    init:
      mode: never