### 선수 퀴즈 맞추기

POST localhost:8080/api/v1/pitcher/submit
Content-Type: application/json

{
  "randomPlayerId": 1,
  "userPlayerId": 1,
  "tryCount": 2
}

### 랜덤 선수 받기

GET localhost:8080/api/v1/pitcher/random
